/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockets;

import java.net.ServerSocket;
import java.net.Socket;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.*;

/**
 *
 * @author Administrador
 */
public class Sockets extends JFrame {

    public Sockets() {
        setUndecorated(true);
        setOpacity(1f);
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(500, 300);
        setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contenedorMsj = new javax.swing.JScrollPane();
        txtMsj = new javax.swing.JTextArea();
        botonEntendido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(102, 0, 0));
        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atencion !");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 20, 290, 52);

        txtMsj.setEditable(false);
        txtMsj.setLineWrap(true);
        txtMsj.setColumns(20);
        txtMsj.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        txtMsj.setRows(5);
        txtMsj.setWrapStyleWord(true);
        txtMsj.setBorder(null);
        contenedorMsj.setViewportView(txtMsj);

        jPanel1.add(contenedorMsj);
        contenedorMsj.setBounds(20, 100, 450, 110);

        botonEntendido.setBackground(new java.awt.Color(102, 0, 0));
        botonEntendido.setFont(new java.awt.Font("Modern No. 20", 1, 12)); // NOI18N
        botonEntendido.setForeground(new java.awt.Color(255, 255, 255));
        botonEntendido.setText("Entendido");
        botonEntendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntendidoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEntendido);
        botonEntendido.setBounds(170, 240, 160, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(496, 296));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 4, 492, 292);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void botonEntendidoActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    public static void main(String[] args) throws Exception {
        ObjectInputStream ois = null;

        Socket cliente = null;
        ServerSocket server = new ServerSocket(9999);
        try {
            while (true) {
                // el ServerSocket me da el Socket
                cliente = server.accept();
                // informacion en la consola
                System.out.println("Se conectaron desde la IP: "
                        + server.getInetAddress());

                // enmascaro la entrada y salida de bytes
                ois = new ObjectInputStream(cliente.getInputStream());

                // leo el mensaje que envia el cliente
                String msj = (String) ois.readObject();
                // creo la alerta y la muestro
                Sockets obj = new Sockets();
                obj.txtMsj.setText(msj);
                obj.setVisible(true);
            }
        } catch (IOException ex) {
           System.out.println("error");
        }finally{
            try{
                server.close();
            }catch(Exception ex){
                System.out.println("error");
            }
        }

    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonEntendido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane contenedorMsj;
    public javax.swing.JTextArea txtMsj;
    // End of variables declaration
}
